Repository mitodl/micromasters, pull requests merged in 2019-11, with the labels that each got.

#4434 HomePage: include information about the alumni benefits
  cms/models.py
  cms/templates/cms/home_page.html
  static/scss/homepage.scss
Labels: Needs Review

#4448 Added mmfin redirect
  config/nginx.conf.erb
Labels: DevOps, Needs Review

#4428 add github templates copied from mitxpro
  .github/ISSUE_TEMPLATE/bug_template.md
  .github/ISSUE_TEMPLATE/config_change_template.md
  .github/ISSUE_TEMPLATE/feature_template.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/PULL_REQUEST_TEMPLATE/rfc_template.md
  .github/pull_request_template.md
Labels: Needs Review

#4452 fix background img on benefits page
  cms/templates/cms/benefits_page.html
Labels: Waiting on Author

#4457 #4455 Home: grow your network
  cms/templates/cms/home_page.html
  static/images/globe-icon.png
  static/scss/homepage.scss
Labels: Needs Review

#4454 acknowledge admin and course team on program page
  cms/blocks.py
  cms/migrations/0040_courseteamtabpage.py
  cms/models.py
  cms/templates/cms/course_team_tab_page.html
  cms/templates/cms/program_page.html
  static/scss/course-team.scss
  static/scss/layout.scss
Labels: Needs Review

#4456 Replace fax no with link to DocuSign
  static/js/components/dashboard/FinancialAidCard.js
  static/js/components/dashboard/FinancialAidCard_test.js
Labels: Needs Review

#4462 Fix styling of the Courses on program page
  static/js/components/CourseListItemWithPopover.js
  static/scss/dashboard/course-row.scss
  static/scss/program-page.scss
Labels: Needs Review

#4471 Update phonenumbers lib
  requirements.in
  requirements.txt
Labels: Needs Review

#4469 remove instructors carousel from course team tab page.
  cms/models.py
  cms/templates/cms/program_page.html
Labels: Waiting on Author

#4458 Commendation Letter for FA program
  dashboard/api.py
  dashboard/api_test.py
  dashboard/utils.py
  grades/api.py
  grades/api_test.py
  grades/management/commands/generate_program_letter.py
  grades/signals.py
  grades/signals_test.py
  static/js/components/ProgressWidget.js
Labels: Waiting on Author
