Repository mitodl/micromasters, pull requests merged in 2021-09, with the labels that each got.

#5033 Update all cache types in update_cache_for_backend
  dashboard/api.py
  dashboard/api_edx_cache.py
  dashboard/api_edx_cache_test.py
  dashboard/api_test.py
  dashboard/factories.py
  dashboard/views_test.py
  seed_data/lib.py
Labels: bug, Waiting on Author

#5035 Update the circular progress to show passed courses
  dashboard/api.py
  dashboard/api_test.py
  dashboard/utils.py
  dashboard/utils_test.py
  static/js/components/ProgressWidget.js
  static/js/components/ProgressWidget_test.js
  static/js/components/StaffLearnerInfoCard.js
  static/js/factories/dashboard.js
  static/js/flow/programTypes.js
  static/js/test_constants.js
  static/js/util/util.js
  static/js/util/util_test.js
Labels: Waiting on Author

#5031 Add MITx Online Login UI + Dashboard Prompts
  cms/templates/cms/benefits_page.html
  cms/templates/cms/home_page.html
  cms/templates/cms/program_page.html
  courses/models.py
  discussions/views_test.py
  ecommerce/factories.py
  micromasters/settings.py
  selenium_tests/auth_test.py
  selenium_tests/redirect_test.py
  static/images/logo-mitxonline.png
  static/js/actions/signup_dialog.js
  static/js/actions/signup_dialog_test.js
  static/js/components/ProgramSelector.js
  static/js/containers/LearnerPage_test.js
  static/js/containers/SignupDialog.js
  static/js/containers/SignupDialog_test.js
  static/js/entry/public.js
  static/js/lib/api.js
  static/js/lib/api_test.js
  static/js/lib/auth_test.js
  static/js/reducers/index.js
  static/js/reducers/signup_dialog.js
  static/js/reducers/signup_dialog_test.js
  static/js/store/configureStore.js
  static/scss/_button.scss
  static/scss/layout.scss
  static/scss/signin-page.scss
  ui/decorators.py
  ui/templates/base_error.html
  ui/templates/header.html
  ui/templates/mitx-online-required.html
  ui/templates/signin.html
  ui/templates/terms_of_service.html
  ui/urls.py
  ui/views.py
  ui/views_test.py
Labels: Waiting on Author

#5032 added resource page and privacy policy page pre-population migration
  cms/blocks.py
  cms/migrations/0004_create_homepage.py
  cms/migrations/0051_resourcepage.py
  cms/migrations/0052_privacy_page_default_data.py
  cms/models.py
  cms/templates/cms/resource_page.html
  static/scss/layout.scss
  static/scss/resource.scss
  ui/templates/footer.html
Labels: Needs Review

#5042 Fix enrollment API backend (#5041)
  dashboard/views.py
  dashboard/views_test.py
  micromasters/factories.py
Labels: Waiting on Author

#5034 fix degree and employment form fields
  static/js/components/EducationForm.js
  static/js/components/EmploymentForm.js
Labels: Needs Review

#5047 Rework login prompts for backends
  courses/models.py
  courses/serializers.py
  courses/serializers_test.py
  courses/views.py
  micromasters/serializers.py
  micromasters/serializers_test.py
  static/js/components/CouponNotificationDialog_test.js
  static/js/components/SocialAuthDialog.js
  static/js/components/SocialAuthDialog_test.js
  static/js/components/dashboard/courses/ProgressMessage.js
  static/js/components/dashboard/courses/ProgressMessage_test.js
  static/js/containers/App.js
  static/js/factories/dashboard.js
  static/js/flow/declarations.js
  static/js/flow/enrollmentTypes.js
  ui/decorators.py
  ui/urls.py
  ui/views.py
  ui/views_test.py
Labels: Needs Review

#5053 update employment form design city field fix
  static/js/components/EmploymentForm.js
Labels: Waiting on Author

#5052 Add Course backend filter in course run admin list
  courses/admin.py
Labels: Waiting on Author

#5055 all DEDP courseware will be on mitxonline
  financialaid/constants.py
Labels: Waiting on Author

#5054 Only prompt for login for enrollable runs (#5051)
  courses/factories.py
  courses/models.py
  courses/models_test.py
  courses/serializers.py
  courses/serializers_test.py
  courses/views.py
  static/js/components/CouponNotificationDialog_test.js
  static/js/components/SocialAuthDialog.js
  static/js/factories/dashboard.js
  static/js/flow/enrollmentTypes.js
Labels: Needs Review

#5057 URL escape usernames for profile urls (#5056)
  dashboard/urls.py
  financialaid/urls.py
  micromasters/urls_test.py
  profiles/constants.py
  profiles/views.py
  ui/urls.py
Labels: Needs Review

#5062 Don't refresh learner dashboards for staff (#5061)
  dashboard/api.py
  dashboard/api_test.py
  dashboard/views.py
  dashboard/views_test.py
  static/js/containers/FinancialAidCalculator_test.js
Labels: Needs Review

#5065 Add support for discontinued runs (#5064)
  courses/admin.py
  courses/migrations/0037_discontinued_course_runs.py
  courses/models.py
  dashboard/models.py
  micromasters/utils_test.py
Labels: Needs Review
