Repository mitodl/micromasters, pull requests merged in 2021-03, with the labels that each got.

#4799 Updated new relic in order to support python 3.9
  requirements.txt
Labels: Waiting on Author

#4796 asadiqbal08/Removed course count block
  cms/templates/cms/home_page.html
Labels: Waiting on Author

#4802 Certificate restyle according to edX
  static/images/certificates/micromasters_certificate_verified_logo.svg
  static/images/certificates/micromasters_certificate_watermark.svg
  static/images/certificates/mitx_certificate_logo.png
  static/images/mm_watermark2.png
  static/scss/certificate.scss
  ui/templates/background-images.css
  ui/templates/certificate.html
Labels: Waiting on Author

#4790 Exam Coupons: use edX coupons when user loads the dashboard
  dashboard/api.py
  dashboard/api_test.py
  exams/admin.py
  exams/factories.py
  exams/management/commands/populate_edx_exam_coupons.py
  exams/migrations/0018_examruncoupon.py
  exams/migrations/0019_examauthorization_exam_coupon.py
  exams/models.py
Labels: Waiting on Author

#4816 Updated heroku stack
  app.json
Labels: DevOps

#4812 add certificate sharing context
  certificates/views.py
  static/images/certificates/mitx_logo_250x250.png
  ui/templates/certificate.html
Labels: Waiting on Author

#4814 Remove ENABLE_EDX_EXAMS feature flag
  dashboard/utils.py
  dashboard/utils_test.py
  static/js/components/dashboard/courses/StatusMessages.js
  static/js/components/dashboard/courses/StatusMessages_test.js
  static/js/global_init.js
  ui/views.py
  ui/views_test.py
Labels: Waiting on Author

#4818 add support for multiple signatories in certificate design
  static/scss/certificate.scss
  ui/templates/certificate.html
Labels: Waiting on Author

#4828 Adding user to raw fields in FinancialAidAdmin
  financialaid/admin.py
Labels: Needs Review

#4829 Update existing FAs with current tier programs
  financialaid/management/commands/migrate_finaid_program_tiers.py
Labels: Needs Review

#4827 Show an error message on checkout request failure
  static/js/components/OrderSummary.js
Labels: Needs Review

#4833 Increase timeout for FinancialAidCalculator tests
  static/js/containers/FinancialAidCalculator_test.js
Labels: Waiting on Author

#4830 Fix sentry Errors -- typeError on Checkout & IE 11.0 forEach error
  static/js/containers/OrderSummaryPage.js
  static/js/entry/public.js
Labels: Waiting on Author

#4841 Missed deadline message for exams
  dashboard/api.py
  dashboard/api_test.py
  exams/models.py
  static/js/components/CouponNotificationDialog_test.js
  static/js/components/dashboard/courses/StatusMessages.js
  static/js/components/dashboard/courses/StatusMessages_test.js
  static/js/factories/dashboard.js
  static/js/flow/programTypes.js
Labels: Needs Review

#4848 changing micromasters certificate logo in program certificate
  static/images/certificates/micromasters_certificate_logo.svg
  static/scss/certificate.scss
  ui/templates/certificate.html
Labels: Waiting on Author

#4822 adding documentation for edX exam management commands
  exams/README.md
Labels: Needs Review

#4844 Restrict exam authorization if user missed payment deadline
  dashboard/utils.py
  exams/api.py
  exams/api_test.py
  exams/utils.py
  exams/utils_test.py
Labels: Waiting on Author
